"use client";
import { FormEvent, useMemo, useState } from "react";

type Entity={id:string;legalName:string;tin:string};
export function InvoiceForm({entities,demo}:{entities:Entity[];demo:boolean}){
 const [entityId,setEntityId]=useState(entities[0]?.id??""); const [ref,setRef]=useState(`MANUAL-${Date.now()}`); const [description,setDescription]=useState(""); const [net,setNet]=useState(""); const [taxBps,setTaxBps]=useState("0"); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const netMinor=useMemo(()=>Math.round(Number(net||0)*100),[net]); const taxMinor=useMemo(()=>Math.round(netMinor*Number(taxBps||0)/10000),[netMinor,taxBps]);
 async function submit(e:FormEvent){e.preventDefault();if(demo){setError("Configure Supabase and a tenant membership before creating live invoices.");return;}setBusy(true);setError("");try{const r=await fetch("/api/dashboard/invoices",{method:"POST",headers:{"content-type":"application/json","idempotency-key":`manual:${ref}`},body:JSON.stringify({legal_entity_id:entityId,source_ref:ref,description,unit_price_minor:netMinor,tax_rate_bps:Number(taxBps)})});const j=await r.json();if(!r.ok)throw new Error(j?.error?.message??"Invoice creation failed");window.location.assign("/invoices");}catch(err){setError(err instanceof Error?err.message:"Invoice creation failed");}finally{setBusy(false);}}
 return <div className="grid-2"><form className="card" onSubmit={submit}><div className="form-grid">
  <label><span className="label">Legal entity</span><select className="input" value={entityId} onChange={e=>setEntityId(e.target.value)} required>{entities.map(x=><option key={x.id} value={x.id}>{x.legalName} · {x.tin}</option>)}</select></label>
  <label><span className="label">Source reference</span><input className="input" value={ref} onChange={e=>setRef(e.target.value)} maxLength={160} required/></label>
  <label><span className="label">Description</span><input className="input" value={description} onChange={e=>setDescription(e.target.value)} maxLength={500} required/></label>
  <label><span className="label">Net amount (ETB)</span><input className="input" inputMode="decimal" value={net} onChange={e=>setNet(e.target.value)} placeholder="1000.00" required/></label>
  <label><span className="label">Tax rate (basis points)</span><input className="input" inputMode="numeric" value={taxBps} onChange={e=>setTaxBps(e.target.value)} required/></label>
 </div>{error?<div className="callout" style={{marginTop:14}} role="alert">{error}</div>:null}<div className="row" style={{marginTop:18}}><div style={{color:"var(--muted)",fontSize:13}}>Creates a validated invoice; fiscal submission is a separate action.</div><button className="btn btn-primary" disabled={busy||!entities.length}>{busy?"Creating…":"Validate invoice"}</button></div></form>
 <div className="card"><h2 className="section-title">Calculated totals</h2><div style={{display:"grid",gap:12,marginTop:18}}><div className="row"><span className="metric-label">Net</span><strong>Br {(netMinor/100).toFixed(2)}</strong></div><div className="row"><span className="metric-label">Tax</span><strong>Br {(taxMinor/100).toFixed(2)}</strong></div><div style={{height:1,background:"var(--line)"}}/><div className="row"><span>Total</span><span className="metric-value" style={{fontSize:22}}>Br {((netMinor+taxMinor)/100).toFixed(2)}</span></div></div><div className="callout" style={{marginTop:18}}>Tax rate is supplied by your configuration/user. The application does not claim a hard-coded rate is authoritative Ethiopian tax law.</div></div></div>;
}
